[features]
seeds = false
skip-lint = false
[programs.devnet]
demo_pda = "9vXBaSaS7cjBGfzNjWGPiyWYjkFjjvoWAe4wWtvaSDew"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/shahrukh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
